variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_datastore" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "vbrserver_name" {}
variable "vbrserver_IP" {}
variable "netmask" {}
variable "def_gw" {}
variable "dns_server" {}
variable "vbrserver_cpu_num" {}
variable "vbrserver_mem" {} 
variable "firmware" {}